name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
      - ".github/workflows/deploy-frontend.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      VITE_DOMAIN_NAME: ${{ secrets.VITE_DOMAIN_NAME }}
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build React app with secret
        run: |
          echo "VITE_DOMAIN_NAME=${{ secrets.VITE_DOMAIN_NAME }}" > .env.production
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build

      - name: Deploy to Domain
        run: npm run deploy
