name: Deploy FastAPI (PM2)

on:
    push:
        branches:
            - main
        paths:
            - "backend/**"

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Copy backend files to server
              uses: appleboy/scp-action@v0.1.7
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.SERVER_USER }}
                  key: ${{ secrets.SSH_KEY }}
                  source: "backend/*"
                  target: "/home/ubuntu/app/backend"

            - name: Install & Restart FastAPI via PM2
              uses: appleboy/ssh-action@v0.1.10
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.SERVER_USER }}
                  key: ${{ secrets.SSH_KEY }}
                  script: |
                      cd /home/ubuntu/app/backend
                      python3 -m venv venv
                      source venv/bin/activate
                      pip install -r requirements.txt
                      pm2 restart ecosystem.config.js || pm2 start ecosystem.config.js
                      pm2 save
